# Basic options

title: HmltConverter
author: kemsty2
email: kemsty2@yahoo.fr
description: HtmlConverter is a wrapper of wkthmltopdf library write in C# and build as a Asp.Net Core libray. It helps you convert Html to PDF or Image. Have fun !!!
twitter_username: kemsty2
github_username: kemsty2

# Build settings
markdown: kramdown
theme: minima
